### ISSUE TITLE
有配套资料吗

### ISSUE THREAD

**Issue by 2556506985** [aomsir/hxds#4]

**Comment by aomsir** [comment]
有

**Comment by 2556506985** [comment]
怎么收费，想要

逆风奔跑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aomsir/hxds"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月3日(星期六) 晚上7:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aomsir/hxds] 有配套资料吗 (Issue #4)





 
有

**Comment by 2556506985** [comment]
他的好贵，我只需要他说的gitee资源和文档资料

**Comment by aomsir** [comment]
去官方买，文档爬不下来，后期项目启动需要使用icode和tcode。这玩意儿2小时更新一次，卖给你我就得把账号给你
