### ISSUE TITLE
项目代码完整吗？

### ISSUE THREAD

**Issue by HandsDylan** [aomsir/hxds#6]
您好，请问这个项目的代码部分完整吗？目前没看到前端的

**Comment by HandsDylan** [comment]
顺便问问后端是完整的吗？谢谢您的回答

**Comment by aomsir** [comment]
后端代码是完整，除了两个加密的jar以外。前端3个工程里面由于硬编码了部分key信息，所以没有公开。

**Comment by HandsDylan** [comment]
> 后端代码是完整，除了两个加密的jar以外。前端3个工程里面由于硬编码了部分key信息，所以没有公开。

明白，因为最近想学习这个项目，能否麻烦您删除掉敏感的信息，私信发一下前端部分呢？ 万分感谢

**Comment by aomsir** [comment]
兄弟，我说句实在的，这项目没必要去看，1299没你想的那么好，200块差不多。里面问题很多，学不到啥东西的，正儿八经不如谷粒商城，这课讲的从第一句开始就在装逼
